### ISSUE TITLE
Establishing "Can Check-in" relationship via Attended Check-in...

### ISSUE THREAD

**Issue by K-Fritsch** [KingdomFirst/rock-attended-checkin#35] opened 2017-10-13 20:35 UTC
**I’ve noticed and issue with Attended Check-in and how it establishes / handles the  “Can Check-in” and “Allow Check-in By” Known Relationships:**
This came about when I was testing how to address check-in situations where a neighbor, or extended family member, brings another church member’s kiddo to church and needs to check them in.  I know we can establish the “Can Check-in” and/or “Allow Check-in By” relationship while logged in as a user in Rock, however, I also want the capability of doing so via the “Attended Check-in” side of things during services.  

That being said, I did some testing by adding a friend’s kiddo (that already existed in our database under his parent’s family) as a visitor via Attended Check-in to my family to see what would happen. It allowed me to check him in AND when I logged into Rock, I saw that it established the “Can Check-in” and inverse “Allow Check-in By” relationship for that child and I.  However, I also noticed that Rock established the “Can check-in” and/or “Allow Check-in By” relationship across ALL people from both mine AND my friend’s families. When I looked in Attended Check-in again, it now showed all these additional kiddos as visitors under my family instead of just the one kiddo. For example, I added my friend’s child as a visitor so I could check him in under my family.  From there, Rock established the check-in relationship across all kids and adults from her household and mine, including anyone else that she already had as a visitor in her family.  

I only wanted it to add the specific person. Is there any way around this?

**Comment by dcs619** [comment] 2017-10-17 03:46
I'm not able to reproduce this issue.  The code is set to [only add visitors](https://github.com/NewSpring/rock-attended-checkin/blob/master/cc_newspring/AttendedCheckin/FamilySelect.ascx.cs#L1232) to members of the current family.  Can you post screenshots of the relationships you're creating? What version of Rock are you running?

**Comment by dcs619** [comment] 2018-05-29 12:53
Closing, not able to reproduce

**Closed by dcs619** 2018-05-29 12:53 UTC
